### ISSUE TITLE
how can I get the paper of this work? thanks!

### ISSUE THREAD

**Issue by Arktis2022** [aitor-martinez-seras/SNN-Automotive-Object-Detection#1]

**Comment by aitor-martinez-seras** [comment]
Please send me a mail to this address: aitor.martinez@tecnalia.com. I will send it to you. In any case, it has been submitted today to arXiv and it will be available soon. It will also be available in the proceedings of the 2023 IEEE Conference on Intelligent Transportation Systems (ITSC 2023).
