### ISSUE TITLE
 Drive not accessible

### ISSUE THREAD

**Issue by MehediAhamed** [aitor-martinez-seras/SNN-Automotive-Object-Detection#2]
I can't download your model.pth files. Drive not accessible

**Comment by aitor-martinez-seras** [comment]
Hi, thanks for showing interest in my work! Try with [this link](https://tecnalia365-my.sharepoint.com/:u:/g/personal/aitor_martinez_tecnalia_com/EXv1oX9q9VZEk9qEAGaivUEBFy3Sa_MNaWgZmcSKq5Y9Jw?e=V3H4vA). 

Confirm me if the link is working so that I change it in the README file. Thanks in advance!

**Comment by MehediAhamed** [comment]
Yes, it is accessible. Thank you so much.
